[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bacon-sci = "0.14.0"
num-bigint = "0.4.4"
num-traits = "0.2.17"
