mod day_1;
mod day_10;
mod day_11;
mod day_12;
mod day_13;
mod day_14;
mod day_15;
mod day_2;
mod day_3;
mod day_4;
mod day_5;
mod day_6;
mod day_7;
mod day_8;
mod day_9;

pub fn run() {
    // println!("========== Day 1 ==========");
    // day_1::run();
    // println!();
    // println!("========== Day 2 ==========");
    // day_2::run();
    // println!();
    // println!("========== Day 3 ==========");
    // day_3::run();
    // println!();
    // println!("========== Day 4 ==========");
    // day_4::run();
    // println!();
    // println!("========== Day 5 ==========");
    // day_5::run();
    // println!();
    // println!("========== Day 6 ==========");
    // day_6::run();
    // println!();
    // println!("========== Day 7 ==========");
    // day_7::run();
    // println!();
    // println!("========== Day 8 ==========");
    // day_8::run();
    // println!();
    // println!("========== Day 9 ==========");
    // day_9::run();
    // println!();
    // println!("========== Day 10 ==========");
    // day_10::run();
    // println!();
    // println!("========== Day 11 ==========");
    // day_11::run();
    // println!();
    // println!("========== Day 12 ==========");
    // day_12::run();
    // println!();
    // println!("========== Day 13 ==========");
    // day_13::run();
    // println!();
    // println!("========== Day 14 ==========");
    // day_14::run();
    // println!();
    println!("========== Day 15 ==========");
    day_15::run();
    println!();
}
